# Generated by Django 2.1.1 on 2018-11-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181126_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='user',
            new_name='group',
        ),
    ]
