# Generated by Django 2.1.1 on 2018-11-27 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181126_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='submission_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
