# Generated by Django 2.1.1 on 2018-11-22 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181122_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='submission_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
