# Generated by Django 2.1.1 on 2018-11-22 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Project_DueDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
