# Generated by Django 2.1.1 on 2018-11-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181122_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='submission_box',
            new_name='submission_Box',
        ),
    ]
