# Generated by Django 2.1.1 on 2018-11-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_submission_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_Box', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='submission_Box',
        ),
    ]
