# Generated by Django 2.1.1 on 2018-11-26 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181126_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='User',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
            preserve_default=False,
        ),
    ]
