# Generated by Django 2.1.1 on 2018-11-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='s_box',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
