# Generated by Django 2.1.1 on 2018-11-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181121_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=128)),
                ('Project_Detail', models.CharField(max_length=128)),
                ('Admin_File_Upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='submission_box',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
