# Generated by Django 2.1.1 on 2018-11-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181121_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Due_dates1',
        ),
        migrations.AddField(
            model_name='admin',
            name='Project_DueDate',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
